# Generated by Django 6.1 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_passwordresettoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category Name (e.g. Kids, Running, Streetwear, Limited Edition)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug (e.g. kids, running). Auto-generated if left blank.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description / tagline for banner', null=True)),
                ('banner_image', models.CharField(blank=True, help_text='Optional banner image URL', max_length=500, null=True)),
                ('icon_class', models.CharField(default='fa-shoe-prints', help_text='FontAwesome icon class (e.g. fa-fire, fa-child, fa-bolt)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Check to activate this category on the website')),
                ('show_in_navbar', models.BooleanField(default=True, help_text='Check to automatically add to top navigation bar')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in navbar / menus (lowest first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
