# Generated by Django 6.1 on 2026-09-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique Product Code or Slug (e.g. aj1-chicago, m1, air-max-90)', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Product Title (e.g. Nike Air Jordan 1 Retro High OG)', max_length=200)),
                ('brand', models.CharField(default='Nike / Jordan', help_text='Brand Name (e.g. Nike, Adidas, Jordan, Puma, New Balance)', max_length=100)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories & Shoe Care'), ('kids', 'Kids & Juniors'), ('unisex', 'Unisex')], default='men', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling Price in INR (₹)', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original MRP before discount', max_digits=10, null=True)),
                ('tag', models.CharField(default='high-top', help_text='Category tags for filters (e.g. high-top, running, basketball, chunky, retro, care, laces)', max_length=100)),
                ('badge_text', models.CharField(blank=True, help_text='Badge label on card (e.g. Bestseller, New Drop, Limited, 20% OFF)', max_length=50, null=True)),
                ('badge_style', models.CharField(choices=[('new', 'New Drop (Neon Orange)'), ('limited', 'Limited Edition (Purple Glow)'), ('sale', 'Hot Deal / Sale (Red)'), ('trending', 'Trending / Bestseller (Emerald Green)')], default='new', max_length=20)),
                ('main_image', models.CharField(default='/static/img/shoe-1.jpg', help_text='Primary shoe image URL or /static path', max_length=500)),
                ('gallery_images', models.TextField(blank=True, help_text='Comma-separated or newline-separated gallery image URLs for multi-angle preview', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed shoe description', null=True)),
                ('features_text', models.TextField(blank=True, help_text='Key features / technology bullet points (one per line)', null=True)),
                ('specs_json', models.TextField(blank=True, help_text='Technical specifications in JSON or Key: Value format', null=True)),
                ('sizes_list', models.CharField(default='UK 6, UK 7, UK 8, UK 9, UK 10, UK 11', help_text='Available shoe sizes (comma-separated)', max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=24)),
                ('stock_quantity', models.PositiveIntegerField(default=20, help_text='Available inventory stock units')),
                ('is_in_stock', models.BooleanField(default=True, help_text='In Stock status')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on Home Page showcase')),
                ('is_trending', models.BooleanField(default=False, help_text='Highlight as trending drop')),
                ('is_active', models.BooleanField(default=True, help_text='Visible in website store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.category')),
            ],
            options={
                'verbose_name': 'Sneaker & Product',
                'verbose_name_plural': 'Sneakers & Products',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
