# Generated by Django 6.1 on 2026-09-25 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer Full Name', max_length=150)),
                ('email', models.EmailField(help_text='Customer Contact Email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact Phone Number', max_length=25, null=True)),
                ('order_id', models.CharField(blank=True, help_text='Related Order ID (if any)', max_length=50, null=True)),
                ('issue_type', models.CharField(choices=[('order_status', 'Order Tracking & Status'), ('return_refund', 'Return / Replacement / Refund'), ('product_defect', 'Damaged or Wrong Item'), ('size_fit', 'Sizing & Fit Query'), ('payment_issue', 'Payment & Billing'), ('general_feedback', 'General Feedback / Inquiries')], default='order_status', max_length=40)),
                ('subject', models.CharField(blank=True, help_text='Subject / Short Topic', max_length=250, null=True)),
                ('message', models.TextField(help_text='Inquiry or issue details from customer')),
                ('status', models.CharField(choices=[('NEW', 'New Inbound Inquiry'), ('IN_PROGRESS', 'In Progress / Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text='Internal Admin notes or resolution reply', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Support Message',
                'verbose_name_plural': 'Customer Support Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
