# Generated by Django 6.1 on 2026-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(blank=True, default='Blue Dart Express (Air Speed)', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, default='110001', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_style',
            field=models.CharField(blank=True, choices=[('new', 'New Drop (Neon Orange)'), ('limited', 'Limited Edition (Purple Glow)'), ('sale', 'Hot Deal / Sale (Red)'), ('trending', 'Trending / Bestseller (Emerald Green)')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Badge label on card', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Nike / Jordan', help_text='Brand Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Unique Product Code (Auto-generated if left blank)', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Shoe description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features_text',
            field=models.TextField(blank=True, help_text='Key features (one per line)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery_images',
            field=models.TextField(blank=True, help_text='Optional gallery image URLs (comma or newline separated)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Visible in store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature on Home Page'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product Title (e.g. Nike Air Jordan 1)', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(blank=True, default=24),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes_list',
            field=models.CharField(blank=True, default='UK 6, UK 7, UK 8, UK 9, UK 10, UK 11', help_text='Available shoe sizes', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs_json',
            field=models.TextField(blank=True, help_text='Technical specifications', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=20, help_text='Stock quantity available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default='high-top', help_text='Category tags for filters', max_length=100),
        ),
    ]
