# Generated by Django 6.1 on 2026-10-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_invoice_number_order_razorpay_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, help_text='Product Code / Slug', max_length=100)),
                ('user_name', models.CharField(help_text='Reviewer Name', max_length=120)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★ (5/5) - Outstanding / Fire'), (4, '★★★★☆ (4/5) - Great Quality'), (3, '★★★☆☆ (3/5) - Average / Good'), (2, '★★☆☆☆ (2/5) - Below Average'), (1, '★☆☆☆☆ (1/5) - Poor / Disappointed')], default=5, help_text='Star Rating (1 to 5)')),
                ('title', models.CharField(blank=True, help_text='Review Headline / Summary', max_length=200, null=True)),
                ('comment', models.TextField(help_text='Detailed review comments')),
                ('review_image', models.FileField(blank=True, help_text='Customer photo of sneaker', null=True, upload_to='review_photos/')),
                ('is_verified_buyer', models.BooleanField(default=True, help_text='Display Verified Buyer Squad Badge')),
                ('is_approved', models.BooleanField(default=True, help_text='Check to make visible on live store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Sneaker Review',
                'verbose_name_plural': 'Customer Sneaker Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
